(function () {
  "use strict";

  const q = (id, topic, question, options, answer, explanation, page, source) => ({
    id, topic, q: question, opts: options, ans: answer, exp: explanation, refPage: page, source,
  });

  window.DENTISTRY_QUESTIONS = [
    q("perio-01", "Periodontology", "What is the typical depth range of a healthy gingival sulcus?", ["0.5–3.0 mm", "4–6 mm", "7–9 mm", "10–12 mm"], 0, "A healthy gingival sulcus is generally about 0.5–3.0 mm deep.", 2, "Master Dentistry PDF p.15"),
    q("perio-02", "Periodontology", "Which finding distinguishes a true periodontal pocket from a false pocket?", ["Attachment loss", "Gingival enlargement", "Plaque alone", "Bleeding alone"], 0, "A true pocket includes attachment loss; a false pocket can be caused by enlargement without attachment loss.", 2, "Master Dentistry PDF p.26"),
    q("perio-03", "Periodontology", "Class I furcation involvement extends horizontally by no more than approximately:", ["1 mm", "3 mm", "6 mm", "9 mm"], 1, "Class I is an initial furcation lesion extending no more than about 3 mm horizontally.", 2, "Master Dentistry PDF p.22"),
    q("perio-04", "Periodontology", "Which feature most strongly supports aggressive periodontitis?", ["Slow progression without family pattern", "Rapid attachment and bone loss with familial aggregation", "Only gingival enlargement", "Caries without attachment loss"], 1, "Rapid attachment loss, rapid bone destruction, and familial aggregation are characteristic features.", 2, "Master Dentistry PDF p.28"),
    q("perio-05", "Periodontology", "The main purpose of scaling and root planing is to remove:", ["Plaque, calculus, and contaminated root-surface material", "Healthy enamel", "Only food debris", "The periodontal ligament"], 0, "SRP removes plaque, calculus, and contaminated or necrotic cementum from root surfaces.", 2, "Master Dentistry PDF pp.115, 55"),

    q("endo-01", "Endodontics & Restorative", "Pain that stops soon after a stimulus is removed is most consistent with:", ["Reversible pulpitis", "Irreversible pulpitis", "Pulp necrosis", "Acute apical abscess"], 0, "Brief, non-lingering pain is more consistent with reversible pulpitis.", 3, "Master Dentistry PDF p.76"),
    q("endo-02", "Endodontics & Restorative", "Why is straight-line root canal access desirable?", ["It increases instrument bending", "It reduces instrument bending and improves apical access", "It seals the canal without obturation", "It removes the need for irrigation"], 1, "Straight-line access reduces bending and helps instruments reach the apical portion of the canal.", 3, "Master Dentistry PDF pp.82–84"),
    q("endo-03", "Endodontics & Restorative", "Sodium hypochlorite is used during root canal treatment mainly because it is:", ["Only a lubricant", "Antimicrobial and tissue dissolving", "A permanent restorative material", "A local anesthetic"], 1, "NaOCl is valued for antimicrobial action and its ability to dissolve organic tissue.", 3, "Master Dentistry PDF p.84"),
    q("endo-04", "Endodontics & Restorative", "A small patency file is used to help:", ["Maintain apical patency", "Increase crown height", "Etch enamel", "Record jaw relations"], 0, "A small file can help prevent apical blockage and maintain canal patency.", 3, "Master Dentistry PDF p.85"),
    q("endo-05", "Endodontics & Restorative", "Mineral trioxide aggregate is commonly used for:", ["Tooth whitening", "Repair procedures and root-end filling", "Alginate impressions", "Orthodontic retention"], 1, "MTA is used in endodontic repair procedures and as a root-end filling material.", 3, "Master Dentistry PDF p.99"),
    q("endo-06", "Endodontics & Restorative", "During setting, glass-ionomer cement should be protected from:", ["Only visible light", "Moisture contamination and desiccation", "All fluoride", "Occlusal adjustment"], 1, "Glass ionomer is vulnerable to both moisture and desiccation while setting.", 3, "Master Dentistry PDF p.117"),
    q("endo-07", "Endodontics & Restorative", "A fissure sealant is most appropriate for a susceptible pit or fissure when:", ["Radiographic dentinal caries is present", "There is no radiographic dentinal caries", "The tooth is avulsed", "The tooth is fully covered by a crown"], 1, "Sealants protect susceptible pits and fissures when radiographic dentinal caries is absent.", 3, "Master Dentistry PDF pp.187–188"),

    q("prostho-01", "Prosthodontics & Sedation", "Kennedy Class I describes:", ["A unilateral bounded saddle", "Bilateral posterior free-end saddles", "A single anterior saddle crossing the midline", "No edentulous area"], 1, "Class I has bilateral posterior edentulous areas, producing bilateral free-end saddles.", 4, "Master Dentistry PDF p.147"),
    q("prostho-02", "Prosthodontics & Sedation", "Kennedy Class III describes:", ["Bilateral free-end saddles", "A unilateral edentulous area bounded by teeth", "An anterior area crossing the midline", "A completely edentulous arch"], 1, "Class III is a unilateral bounded edentulous area with teeth anterior and posterior to it.", 4, "Master Dentistry PDF p.147"),
    q("prostho-03", "Prosthodontics & Sedation", "An overdenture gains support by covering:", ["Only soft tissue", "Retained teeth, roots, or implants", "The tongue", "The opposing denture only"], 1, "An overdenture covers and gains support from retained teeth, roots, or implants.", 4, "Master Dentistry PDF pp.146–147"),
    q("prostho-04", "Prosthodontics & Sedation", "The altered-cast technique is used mainly to compensate for different support from:", ["Enamel and dentin", "Abutment teeth and mucosa", "Upper and lower lips", "Pulp and periodontal ligament"], 1, "It helps reconcile the differing support provided by abutment teeth and mucosa in distal-extension cases.", 4, "Master Dentistry PDF p.151"),
    q("prostho-05", "Prosthodontics & Sedation", "Which gas combination is used for inhalation conscious sedation?", ["Nitrous oxide with oxygen", "Carbon dioxide with nitrogen", "Helium with oxygen only", "Methane with air"], 0, "Nitrous oxide with oxygen provides rapid-onset conscious sedation while the patient remains responsive.", 4, "Master Dentistry PDF p.166"),
    q("prostho-06", "Prosthodontics & Sedation", "Flumazenil reverses drugs in which class?", ["Benzodiazepines", "Local anesthetics", "NSAIDs", "Antibiotics"], 0, "Flumazenil is a benzodiazepine antagonist.", 4, "Master Dentistry PDF pp.164–165"),

    q("pedo-01", "Pediatric Dentistry & Trauma", "A pulpotomy removes:", ["Only the coronal pulp", "Only the radicular pulp", "All enamel", "The entire tooth"], 0, "A pulpotomy removes inflamed coronal pulp while preserving radicular pulp tissue.", 5, "Master Dentistry PDF p.197"),
    q("pedo-02", "Pediatric Dentistry & Trauma", "A pulpectomy removes:", ["Only coronal pulp", "Coronal and radicular pulp", "Only periodontal tissue", "Only a carious lesion"], 1, "A pulpectomy removes both coronal and radicular pulp tissue before obturation.", 5, "Master Dentistry PDF p.199"),
    q("pedo-03", "Pediatric Dentistry & Trauma", "Apexification aims to create:", ["A new crown", "An apical hard-tissue barrier", "An orthodontic space", "A periodontal pocket"], 1, "Apexification creates an apical hard-tissue barrier in an immature non-vital tooth.", 5, "Master Dentistry PDF pp.200–201"),
    q("pedo-04", "Pediatric Dentistry & Trauma", "What is the usual management principle for an avulsed primary tooth?", ["Replant immediately", "Do not replant", "Store for six months", "Prepare for a crown"], 1, "Replantation is generally not recommended because it can harm the permanent successor.", 5, "Master Dentistry PDF pp.212–214"),
    q("pedo-05", "Pediatric Dentistry & Trauma", "Subluxation is best described as:", ["Intrusion into bone", "Loosening without displacement", "Complete avulsion", "Crown fracture with pulp exposure"], 1, "Subluxation is increased mobility or loosening without displacement.", 5, "Master Dentistry PDF p.210"),
    q("pedo-06", "Pediatric Dentistry & Trauma", "Dens invaginatus most commonly affects which permanent tooth?", ["Mandibular canine", "Maxillary lateral incisor", "Mandibular first molar", "Maxillary central incisor only"], 1, "This developmental invagination commonly affects maxillary lateral incisors.", 5, "Master Dentistry PDF p.219"),

    q("ortho-01", "Orthodontics", "A normal overjet is approximately:", ["0 mm", "2–4 mm", "6–8 mm", "10–12 mm"], 1, "The source gives a normal overjet range of about 2–4 mm.", 6, "Master Dentistry PDF p.242"),
    q("ortho-02", "Orthodontics", "The Index of Orthodontic Treatment Need has which two components?", ["Dental health and aesthetic", "Pulpal and periodontal", "Medical and surgical", "Occlusal and endodontic"], 0, "IOTN combines a dental health component with an aesthetic component.", 6, "Master Dentistry PDF pp.243–244"),
    q("ortho-03", "Orthodontics", "How is the ANB angle calculated?", ["SNA + SNB", "SNA − SNB", "SNB − SNA", "SNA × SNB"], 1, "ANB equals SNA minus SNB.", 6, "Master Dentistry PDF pp.253–254"),
    q("ortho-04", "Orthodontics", "Class II division 1 commonly includes:", ["Reduced overjet", "Increased overjet", "No overjet", "Posterior crossbite only"], 1, "An increased overjet is a common feature of Class II division 1.", 6, "Master Dentistry PDF p.280"),
    q("ortho-05", "Orthodontics", "Growth-modifying functional appliances are generally timed around:", ["Infancy", "Late mixed dentition while growth remains", "After all growth has ceased", "Only after age 40"], 1, "They are generally used around late mixed dentition while useful growth remains.", 6, "Master Dentistry PDF pp.259, 318"),

    q("stats-01", "Biostatistics", "The standard error of the mean is calculated as:", ["SD × √n", "SD ÷ √n", "Mean ÷ SD", "Variance × n"], 1, "Standard error equals the standard deviation divided by the square root of sample size.", 7, "Dental Pulse PDF p.5"),
    q("stats-02", "Biostatistics", "In a symmetric normal distribution, which measures are equal?", ["Range and variance", "Mean, median, and mode", "Sensitivity and specificity", "Risk and odds"], 1, "Mean, median, and mode coincide in a symmetric normal distribution.", 7, "Dental Pulse PDF pp.5, 15"),
    q("stats-03", "Biostatistics", "Which test is commonly used to compare proportions or categorical frequencies?", ["Chi-square", "Paired t-test", "ANOVA", "Pearson correlation only"], 0, "Chi-square tests association or differences involving categorical data and proportions.", 7, "Dental Pulse PDF pp.4–5"),
    q("stats-04", "Biostatistics", "Which test compares before-and-after measurements in the same participants?", ["Independent t-test", "Paired t-test", "Chi-square only", "One-way ANOVA only"], 1, "A paired t-test compares two related measurements, such as before and after values in the same group.", 7, "Dental Pulse PDF pp.4–5"),
    q("stats-05", "Biostatistics", "One-way ANOVA is used to compare:", ["Two proportions only", "Means of three or more groups", "One patient over time", "Only nonnumeric data"], 1, "One-way ANOVA compares means across three or more groups.", 7, "Dental Pulse PDF p.5"),
    q("stats-06", "Biostatistics", "A Type II error occurs when a researcher:", ["Rejects a true null hypothesis", "Fails to reject a false null hypothesis", "Accepts every alternative", "Uses a large sample"], 1, "A Type II error is failing to reject a false null hypothesis.", 7, "Dental Pulse PDF pp.4–5"),

    q("epi-01", "Epidemiology & Indices", "Incidence measures:", ["All existing cases only", "New cases occurring over a period", "Only deaths", "Only treatment outcomes"], 1, "Incidence counts new cases arising in a defined population over a specified period.", 8, "Dental Pulse PDF p.23"),
    q("epi-02", "Epidemiology & Indices", "Prevalence measures:", ["The proportion affected at a point or during a period", "Only newly diagnosed cases", "Only exposed persons", "Only recovered cases"], 0, "Prevalence describes how much of a population is affected at a point or during a period.", 8, "Dental Pulse PDF p.23"),
    q("epi-03", "Epidemiology & Indices", "Which measure is commonly estimated by a case-control study?", ["Relative risk directly", "Odds ratio", "Incidence density only", "Mean difference only"], 1, "Case-control studies usually estimate association with an odds ratio.", 8, "Dental Pulse PDF pp.23, 31"),
    q("epi-04", "Epidemiology & Indices", "Which study design can directly calculate relative risk?", ["Case report", "Cohort study", "Cross-sectional survey only", "Ecological study only"], 1, "A cohort follows exposed and unexposed groups over time and can directly calculate relative risk.", 8, "Dental Pulse PDF pp.21, 23"),
    q("epi-05", "Epidemiology & Indices", "DMFT records permanent teeth that are:", ["Decayed, missing due to caries, or filled", "Only mobile", "Only unerupted", "Only crowned"], 0, "DMFT summarizes decayed, missing because of caries, and filled permanent teeth.", 8, "Dental Pulse PDF pp.44–46"),
    q("epi-06", "Epidemiology & Indices", "CPITN/CPI uses which instrument?", ["WHO periodontal probe", "Endodontic spreader", "Fox plane", "Facebow"], 0, "The index uses a WHO probe to record bleeding, calculus, and periodontal pockets.", 8, "Dental Pulse PDF pp.45–46"),

    q("prev-01", "Prevention & Caries", "A common fluoride concentration for dentifrice in the supplied reference is approximately:", ["100 ppm", "500 ppm", "1000 ppm", "10,000 ppm"], 2, "The reference identifies about 1000 ppm fluoride as a common dentifrice concentration.", 9, "Dental Pulse PDF p.60"),
    q("prev-02", "Prevention & Caries", "Which sodium fluoride rinse schedule appears in the supplied reference?", ["0.05% daily or 0.2% weekly", "2% every hour", "10% monthly", "25% once yearly"], 0, "The supplied reference lists 0.05% sodium fluoride daily or 0.2% weekly.", 9, "Dental Pulse PDF p.61"),
    q("prev-03", "Prevention & Caries", "The Vipeholm study is associated with the relationship between caries and:", ["Sugar consistency and frequency", "Tooth color", "Occlusal force", "Local anesthetic duration"], 0, "Vipeholm examined how sugar consistency and frequency relate to dental caries.", 9, "Dental Pulse PDF pp.64, 74"),
    q("prev-04", "Prevention & Caries", "The Turku sugar study examined:", ["Implant loading", "Sugar substitutes such as xylitol", "Fluoride toxicity only", "Orthodontic anchorage"], 1, "The Turku study examined sugar substitutes, including xylitol, and dental caries.", 9, "Dental Pulse PDF p.74"),
    q("prev-05", "Prevention & Caries", "The Snyder test is a caries-activity test based on:", ["Acid production and color change", "Radiographic bone height", "Tooth mobility", "Pulp vitality only"], 0, "The Snyder test is a colorimetric caries-activity test based on acid production.", 9, "Dental Pulse PDF pp.85–86"),
    q("records-01", "Clinical Records", "SOAP stands for:", ["Subjective, Objective, Assessment, Plan", "Screening, Occlusion, Anesthesia, Prevention", "Source, Outcome, Analysis, Procedure", "Symptoms, Oral exam, Advice, Prognosis"], 0, "SOAP is Subjective, Objective, Assessment, and Plan.", 10, "Dental Pulse PDF p.92"),
  ];

  window.DENTISTRY_STUDY_ITEMS = window.DENTISTRY_QUESTIONS.map((item) => ({
    topic: item.topic,
    term: item.q,
    definition: item.exp,
    refPage: item.refPage,
    source: item.source,
  }));
})();
